# Generated by Django 6.0 on 2025-12-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncall',
            name='annc_url',
            field=models.URLField(max_length=2000, unique=True, verbose_name='공고 URL'),
        ),
    ]
