# Generated by Django 6.0 on 2025-12-08 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_anncall_annc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncfiles',
            name='annc_id',
            field=models.ForeignKey(db_column='annc_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.anncall', verbose_name='공고 ID'),
        ),
        migrations.AlterField(
            model_name='docchunks',
            name='annc_id',
            field=models.ForeignKey(db_column='annc_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.anncall', verbose_name='공고 ID'),
        ),
        migrations.AlterField(
            model_name='docchunks',
            name='file_id',
            field=models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.anncfiles', verbose_name='공고 파일 ID'),
        ),
    ]
