# Generated by Django 6.0 on 2025-12-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_anncfiles_annc_id_alter_docchunks_annc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncfiles',
            name='file_path',
            field=models.CharField(max_length=2000, null=True, verbose_name='공고 파일 경로'),
        ),
    ]
