# Generated by Django 6.0 on 2025-12-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_anncfiles_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncall',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='공고 생성 일자'),
        ),
        migrations.AlterField(
            model_name='anncall',
            name='updated_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='공고 수정 일자'),
        ),
    ]
