# Generated by Django 6.0 on 2025-12-08 08:25

import chatbot.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_add_docchunks_fts_vector_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchunks',
            name='fts_vector',
            field=chatbot.models.TSVectorField(blank=True, null=True, verbose_name='전문 검색 벡터'),
        ),
    ]
