---
openapi: 3.0.0
info:
  title: 공고 정보 조회 API
  version: v1.0.0
  description: 다양한 조건을 활용하여 현재 등록된 공고 목록을 페이지별로 조회합니다.
# servers:
#   - url: https://api.yourcompany.com/api
#     description: 프로덕션 서버 기본 URL
paths:
  /anncs:
    get:
      summary: 공고 목록 조회
      operationId: getAnnouncementList
      tags:
        - Announcements
      parameters:
        - name: annc_title
          in: query
          description: 공고 제목 검색 키워드
          required: false
          schema:
            type: string
        - name: annc_status
          in: query
          description: 공고 상태 (예 - 진행중, 마감)
          required: false
          schema:
            type: string
            enum:
              - 진행중
              - 마감
              - 예정
        - name: annc_type
          in: query
          description: 공고 타입 (예 - 채용, 이벤트)
          required: false
          schema:
            type: string
        - name: items_per_page
          in: query
          description: 한 페이지당 표시할 항목 수 (페이지네이션)
          required: true
          schema:
            type: integer
            default: 10
        - name: current_page
          in: query
          description: 현재 요청하는 페이지 번호 (1부터 시작)
          required: true
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: 성공적으로 공고 목록을 조회했습니다.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnnouncementListSuccess"
        "400":
          description: 요청 데이터 유효성 검사 실패
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    AnnouncementListSuccess:
      type: object
      properties:
        message:
          type: string
          description: 요청 처리 결과 메시지
          example: 공고 데이터 조회를 성공적으로 완료했습니다.
        status:
          type: string
          description: 응답 상태 (success)
          example: success
        total_count:
          type: integer
          description: 필터링 조건에 맞는 전체 공고 수
          example: 35
        page_info:
          $ref: "#/components/schemas/PageInfo"
        anncs:
          type: array
          items:
            $ref: "#/components/schemas/AnnouncementItem"
    PageInfo:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        items_per_page:
          type: integer
          example: 10
        total_pages:
          type: integer
          example: 4
    AnnouncementItem:
      type: object
      properties:
        annc_id:
          type: integer
          description: 공고 고유 ID
          example: 1
        annc_title:
          type: string
          description: 공고 제목
          example: 2025년 상반기 신입사원 공개 채용
        annc_url:
          type: string
          description: 공고 상세 페이지 URL
          format: url
          example: https://example.com/announcements/annc_001
        created_dttm:
          type: string
          description: 생성 일시 (UTC)
          format: date-time
        annc_status:
          type: string
          description: 공고 진행 상태
          example: 진행중
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: 오류 상세 메시지
          example: 요청 데이터의 유효성 검사에 실패했습니다.
        status:
          type: string
          description: 응답 상태 (error)
          example: error
